- README.md
- lib/family.h
- lib/registry.cc
- lib/registry.h
- tests/benchmark/counter_bench.cc
- tests/benchmark/gauge_bench.cc
- tests/benchmark/histogram_bench.cc
- tests/benchmark/registry_bench.cc
- tests/family_test.cc
- tests/registry_test.cc
> Make registries and families thread safe

- .gitmodules
- CMakeLists.txt
- cmake/FindGoogleBenchmark.cmake
- cmake/FindTelegraf.cmake
- lib/CMakeLists.txt
- tests/CMakeLists.txt
- tests/benchmark/CMakeLists.txt
- tests/integration/CMakeLists.txt
Works on macOS with ``brew install cmake protobuf google-benchmark`` as a prerequisite.
> Add CMake build

- .travis.yml
This change builds the library using CMake in addition to Bazel.
> Build with CMake in CI

- tests/histogram_test.cc
> Add test for histogram count accumulation

- tests/registry_test.cc
> Add histogram family unit test

- include/prometheus/exposer.h
- lib/exposer.cc
* URI defaults to /metrics
* Fixes #49
> Made the exposer URI configurable

- lib/histogram.cc
> assert histogram buckets are sorted

- repositories.bzl
> civetweb: Add file_ops textual header

- CMakeLists.txt
> Hide civetweb symbols in shared lib

- CMakeLists.txt
- pull/CMakeLists.txt
- pull/src/handler.cc
> pull: Add support for gzip compression

- pull/src/handler.cc
> pull: Send out missing gzip header

- push/include/prometheus/gateway.h
- push/src/gateway.cc
> Refactor push code

- core/BUILD.bazel
- pull/BUILD.bazel
- push/BUILD.bazel
> Bazel: Also build shared libraries

- bazel/zlib.BUILD
- pull/BUILD.bazel
> bazel: rename zlib cc_library to z

- README.md
> Document C++ language requirements

- .travis.yml
> Run promtool check metrics for OSX bazel

- push/src/gateway.cc
> Fix use after free in push gateway

- README.md
> Fix dependency in README

- README.md
Some minor changes to make the example work correctly.
> Update README.md example.

- cmake/FindGoogleBenchmark.cmake
> cmake: Link Google Benchmark library against pthread

- core/src/text_serializer.cc
- core/tests/CMakeLists.txt
- core/tests/serializer_test.cc
> core: Serialize floating values locale-independent

- CMakeLists.txt
> Fix build with MSVC and CMake 3.10

- README.md
Updated README to be consistent with sample_server.cc. README example won't compile since pull request #291
> add include

- .github/scripts/run-bazel-test
- .github/scripts/run-bazel-test.cmd
- .github/scripts/run-cmake-test
- .github/scripts/run-cmake-test.cmd
- .github/scripts/run-prepare
- .github/scripts/run-prepare.cmd
- .github/workflows/continuous-integration-workflow.yml
- .travis.yml
- core/tests/serializer_test.cc
Basic CI like compile and test was migrated to github actions. Code coverage and doxygen generation is still on travis because it depends on secrets managed by @jupp0r.
> Use GitHub actions

- .github/workflows/continuous-integration-workflow.yml
- .github/workflows/coverage.yml
See https://github.com/actions/checkout#Checkout-submodules
> Fix submodule checkout

- CMakeLists.txt
- core/include/prometheus/collectable.h
- core/include/prometheus/detail/time_window_quantiles.h
- core/include/prometheus/family.h
- core/include/prometheus/registry.h
- core/include/prometheus/summary.h
- core/src/detail/time_window_quantiles.cc
- core/src/family.cc
- core/src/registry.cc
- core/src/summary.cc
Collect methods should not influence the state of the objects in any
externally visible way.
> Make Collect methods const

- core/tests/CMakeLists.txt
- pull/include/prometheus/exposer.h
- pull/src/exposer.cc
- pull/tests/CMakeLists.txt
- pull/tests/unit/BUILD.bazel
- pull/tests/unit/CMakeLists.txt
- pull/tests/unit/exposer_test.cc
> feat(pull): Add getter for listening ports

- pull/CMakeLists.txt
> pull: work-around missing winsock lib in civetweb

- core/include/prometheus/family.h
- core/src/family.cc
- core/tests/check_names_test.cc
- core/tests/family_test.cc
> core: enforce proper metric and label names

- CMakeLists.txt
- pull/include/prometheus/exposer.h
- pull/src/endpoint.cc
- pull/src/endpoint.h
- pull/src/exposer.cc
- pull/src/handler.cc
- pull/src/handler.h
- pull/tests/integration/integration_test.cc
> Remove collectable

- README.md
- pull/tests/integration/sample_server.cc
- pull/tests/integration/scrape.sh
> pull: Add better example

- core/src/family.cc
- core/tests/family_test.cc
> core: reject duplicate label names

- pull/src/handler.cc
- pull/tests/integration/integration_test.cc
> pull: Announce utf-8 content encoding

- push/src/gateway.cc
> push: Always use POST (regardless of body presence)

- pull/include/prometheus/exposer.h
- pull/src/exposer.cc
Signed-off-by: kuvaldini <ivan@kuvaldini.pro>
> Add CivetCallbacks to Exposer ctor, closes #479

- cmake/civetweb-3rdparty-config.cmake
- pull/CMakeLists.txt
> pull: Install header files for embedded civetweb

- core/src/text_serializer.cc
> fix(core): Locale-independent floating-point serialization

- core/src/gauge.cc
Issue: #293
Issue: #526
Issue: #531
> docs(core): Document atomic increment

- CMakeLists.txt
- README.md
> docs: Prepare for 1.0.0 release

- pull/include/prometheus/exposer.h
- pull/src/exposer.cc
> fix(pull): Properly lock Exposer functions

- core/include/prometheus/registry.h
- core/src/registry.cc
- core/tests/registry_test.cc
> feat(core): Allow to remove a Family from their Registry

- push/include/prometheus/gateway.h
- push/src/gateway.cc
> feat(push): Add method to delete metrics for instance

- CMakeLists.txt
- cmake/prometheus-cpp-core.pc.in
- cmake/prometheus-cpp-pull.pc.in
- cmake/prometheus-cpp-push.pc.in
- core/CMakeLists.txt
- pull/CMakeLists.txt
- push/CMakeLists.txt
> fix: handle absolute paths in pkgconfig files

- .bazelrc
- .github/workflows/bazel-ci.yml
- bazel/civetweb.BUILD
- bazel/repositories.bzl
> feat(pull): Add SSL support to Bazel build

- CMakeLists.txt
- README.md
> docs: state C++14 requirement

- core/src/gauge.cc
Small contribution, hoping that it might be a bit faster when using recent compilers/C++ dialiects.
> Use std::atomic::fetch_add in modern C++.

- .github/workflows/bazel-ci.yml
- MODULE.bazel
- WORKSPACE.bzlmod
- bazel/repositories.bzl
- bazel/zlib.BUILD
- pull/BUILD.bazel
Issue: #225 #507 #513 #581
Closes: #616
> build(bazel): use Bazel modules

- core/src/registry.cc
> feat(core): optimize add

- core/benchmarks/histogram_bench.cc
> test(core): properly declare manual time

- MODULE.bazel
- MODULE.bazel.lock
- bazel/civetweb.BUILD
- bazel/repositories.bzl
> Fixing #699. Also spotted that @//conditions was used instead of //conditions.

- MODULE.bazel
- MODULE.bazel.lock
- bazel/civetweb.BUILD
- bazel/repositories.bzl
- pull/BUILD.bazel
> Use civetweb as bazel_dep

- push/include/prometheus/gateway.h
- push/src/gateway.cc
> feat(push): allow any url prefix for push gateway
