- lib/exposer.cc
- lib/exposer.h
> Add debug and json http responses

- .travis.yml
- README.md
- WORKSPACE
- tests/benchmark/BUILD
- tests/benchmark/benchmark_helpers.cc
- tests/benchmark/benchmark_helpers.h
- tests/benchmark/counter_bench.cc
- tests/benchmark/gauge_bench.cc
- tests/benchmark/histogram_bench.cc
- tests/benchmark/main.cc
- tests/benchmark/registry_bench.cc
This change adds microbenchmarks for various features of the library
- counter
- incrementing
- collecting
- gauge
- incrementing
- decrementing
- setting to current time
- collecting
- histogram
- observing values for different bucket sizes
- collecting for differnet bucket sizes
- registry
- creating families
- creating metrics inside families with different numbers of label pairs
These benchmarks will come in handy optimizing the library in case any
performance bottlenecks are discovered later.
The benchmarks that matter (incrementing counters, observing histogram
values, ...) show results in the 10s to 100s of nanoseconds, which
looks very good already.
> Add benchmarks

- README.md
- WORKSPACE.example
Documentation on how to consume prometheus-cpp provided in the README
were faulty. This change fixes documentation and resolves #25.
> Fix build documentation

- lib/histogram.cc
- tests/histogram_test.cc
This change makes histogram collection produce cumulative
histograms[1].  The previous implementation collected non-cumulative
histograms, which did not conform to the prometheus specification[2].
Fixes #43.
[1]: https://en.wikipedia.org/wiki/Histogram#Cumulative_histogram
[2]: https://prometheus.io/docs/concepts/metric_types/#histogram
> Make histograms cumulative

- include/prometheus/exposer.h
Prevents accidental conversion from std::string to Exposer
Relates to issue #51
> Exposer constructor marked explicit

- include/prometheus/histogram_builder.h
- lib/histogram_builder.cc
HistogramBuilder did not pass bucket boundaries as a default to
families. I'm removing it, as bucket boundaries can be set
independently when creating histograms from families.
Fixes #46
> Remove unused bucket option on histogram builder

- .travis.yml
- BUILD
- include/prometheus/check_names.h
- include/prometheus/family.h
- lib/CMakeLists.txt
- lib/check_names.cc
- tests/BUILD
- tests/CMakeLists.txt
- tests/check_names_test.cc
- tests/family_test.cc
In order to catch errors in metric and label naming early, this change
adds checks according to the prometheus specification at
https://prometheus.io/docs/concepts/data_model/. In order to minimize
runtime overhead in production, these checks are only performed for
debug builds. Bazel and CMake use `-DNDEBUG` for release builds.
This fixes #57 and #58.
> Check metric and label names

- lib/exposer.cc
This change reduces the number of threads configured for the embedded
http server that prometheus queries on scrapes. The previous (default)
setting is 50 worker threads, which is excessive and unnecessary for
metrics use cases.
> Reduce number of threads for scrape server

- lib/text_serializer.cc
https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details
Integration test passes. We also deployed this patch to our cluster and prometheus is able to scrape the metrics.
> Support prometheus official text format (fixes #9)

- lib/histogram.cc
- tests/histogram_test.cc
Boundary value should be inclusive to make it consistent with other `Prometheus` clients:
* `Java` https://github.com/prometheus/client_java/blob/fb4161a2be99074f1d2fd254238193afa4aa0398/simpleclient/src/main/java/io/prometheus/client/Histogram.java#L238
* `Golang` https://github.com/prometheus/client_golang/blob/661e31bf844dfca9aeba15f27ea8aa0d485ad212/prometheus/histogram.go#L250 where
```go
func SearchFloat64s(a []float64, x float64) int {
return Search(len(a), func(i int) bool { return a[i] >= x })
}
```
* `Python` https://github.com/prometheus/client_python/blob/24d4d95d3fee82e1b5d8679b69b340dab5815eed/prometheus_client/core.py#L891
* `Ruby` https://github.com/prometheus/client_ruby/blob/726512562b354995ab4d325bc4f654833eb225e5/lib/prometheus/client/histogram.rb#L29
> Histogram boundary value should be inclusive

- repositories.bzl
bazel 0.9.0 no longer accepts abridged/md5 hashes.
> Fix build compatibility with bazel 0.9.0

- CMakeLists.txt
- lib/CMakeLists.txt
This is small fix for issue I had when compiling (in my slightly particular environment): linking with old system ZLib instead of the one I wanted.
libprotobuf.so: undefined reference to `deflate'
libprotobuf.so: undefined reference to `deflateEnd'
libprotobuf.so: undefined reference to `inflate'
libprotobuf.so: undefined reference to `inflateInit2_'
libprotobuf.so: undefined reference to `inflateEnd'
> Fix link issue with ZLib

- BUILD
- README.md
- include/prometheus/registry.h
- include/prometheus/summary.h
- include/prometheus/summary_builder.h
- lib/CMakeLists.txt
- lib/handler.cc
- lib/handler.h
- lib/registry.cc
- lib/summary.cc
- lib/summary_builder.cc
- tests/BUILD
- tests/CMakeLists.txt
- tests/benchmark/BUILD
- tests/benchmark/CMakeLists.txt
- tests/benchmark/summary_bench.cc
- tests/summary_test.cc
**Issue:** The summary metric type is not implemented, see #4
This implements the summary type. It uses the same implementation as the [java client](https://github.com/prometheus/client_java)
For not it's still work in progess, since I'll want to do some testing in our dev/prod environment and maybe find some performance improvements.
> WIP: implement summary metric

- repositories.bzl
To enable projects that include prometheus-cpp to optionally exclude the civetweb cpp wrapper library as a direct dependency.
In my case I'm building a web-app based on civetweb, but don't want to link with the c++ wrapper.
> split civetweb into c and c++ libraries

- README.md
git_repository is deprecated--Bazel recommends http_archive where possible, as it is faster and better supported internally (https://docs.bazel.build/versions/master/be/workspace.html#git_repository).
> Switch bazel WORKSPACE instructions from git_repository to http_archive.

- include/prometheus/summary.h
This patch fix error: implicit instantiation of undefined template
`std::__1::array<double, 500>` when it is compiled using Clang on osx.
> Fix implicit instantiation of undefined template

- lib/check_names.cc
GNU libstdc++ prior to GCC 4.9 immediately throws.
Visual Studio 2013 messes up static initialization.
Closes #66
> Prevent usage of broken regex implementation

- README.md
- WORKSPACE
> Use canonical name for Bazel workspace

- lib/text_serializer.cc
Compiler is: "gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609"
The import of `<limits>` is required to use `std::numeric_limits`
> Fix compilation on ubuntu 16.04

- lib/summary.cc
This change fixes a gcc warning about an unitialized std::array
in the summary implementation. Fixes #102.
> Fix uninitialized buffer causing compiler warnings

- include/prometheus/summary.h
This change fixes #107 by adding a missing include causing
compile erros on GCC 7. Thanks to Romain Sertelon for reporting this.
> Fix GCC 7 compile error

- core/include/prometheus/serializer.h
- core/include/prometheus/text_serializer.h
- core/src/text_serializer.cc
- push/BUILD.bazel
- push/include/prometheus/gateway.h
- push/src/gateway.cc
- push/tests/integration/BUILD.bazel
- push/tests/integration/push_client.cc
- push/tests/integration/sample_client.cc
- repositories.bzl
This is based on #113 (and on #123). I hope I addressed all open issues. I moved the hostname retrieval outside of the library because it is platform dependent code and one might want to customize it. On Windows one also has to do the "Winsock init dance".
What I'm unsure about is the selection of cpr as a http library. It's not available in Ubuntu or Homebrew. Maybe adding it as submodule like it was done for civetweb is the way to go. But CMake support will follow in another PR.
> Add push library

- core/src/text_serializer.cc
According to the [Prometheus text exposition format][1] each quantile
named x is given as a separate line with the same name x and a label
{quantile="y"}.
But current Prometheus C++ implementation serializes summary named x
with a name x + "_quantile" for each quantile. This is off spec.
[1]: https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md
> Fix summary text format according to specs.

- .bazelignore
> Remove .bazelignore to prevent Bazel 0.17.1 from crashing

- CMakeLists.txt
Hi,
This fixes a mistake that unfortunately I see far too often in small cmake projects: -std=c++11 is being artibrarily forced to some values
Normally big organisations like mine do rebuild everything themselves and make sure that they control the C++ standard flags used all over all their compilation units. Indeed while quite close, C++11, C++14, C++17 and C++20 are both binary and source incompatible with each other. Compiling prometheus-cpp with C++11 while we actually use C++17 in all our own software otherwise may work, but is a good way to look for tricky problems to investigate in case things like STL containers passed from one C++17 binary to a C++11 binary are actually binary incompatible. This effect is even more true in presence of LTO builds (which we do as well) where it's …
> Allow people who have well defined CXXFLAG with -std=gnu++17 to use it safely if they want to

- README.md
- pull/src/handler.cc
- pull/tests/integration/BUILD.bazel
- pull/tests/integration/lint.sh
- pull/tests/integration/sample_server.cc
- pull/tests/integration/scrape.sh
- push/tests/integration/sample_client.cc
The sample_server is now `promtool check`-clean.
See: https://prometheus.io/docs/practices/naming/
Issue: #89
> Breaking Change: Use recommended metric naming

- README.md
see 01a8e63c3d70fcb65e0143b362a6705e391b32ea
> docs: benchmarks moved to top-level

- pull/include/prometheus/exposer.h
- pull/src/exposer.cc
- pull/tests/integration/sample_server.cc
Exposer class creates two threads by default which could be too much in some cases. This pull-request allows to configure number of threads used by an exposer.
> configure number of threads used by Exposer

- core/include/prometheus/family.h
**Background:**
I'm using prometheus-cpp to expose metrics from a program. I don't want to cache metrics within the program because we have a large number of metrics and that would be difficult to manage, and prometheus-cpp already provides caching function in `Family<T>::Add`. Since I'm not caching metrics, I don't know which metrics have already been created and which haven't, so I always call `Add`  before `Increment`/`Set`/`Observe`.
e.g.
```
prometheus::Counter& counter = counter_family.Add({{"foo", "bar"}});
counter.Increment();
```
**Problem:**
I did some analysis of my program and found that it was spending more time doing stat updates than what I expected from your benchmarks. The majority of this time was spent in the `CheckLabelName` function which is called by …
> Only check label names when inserting a metric into a family

- README.md
Was trying to find some docs and couldn't find anything until I found #11. Think it would be easier if there was a link in the readme
> Add link to jupp0r.github.io/prometheus-cpp

- core/include/prometheus/histogram.h
- core/src/histogram.cc
- core/tests/histogram_test.cc
Added the ObserveMultiple method to the Histogram. This is useful
if you have already have values sorted into buckets, and the sum of
the values but no longer have the individual values.
> Allow more than 1 histogram observation at a time

- .github/workflows/continuous-integration-workflow.yml
Github updates the macos fleet to catalina and recommends
to stay on macos-latest.
> fix(github): Use macos-latest

- .github/workflows/coverage.yml
Looks like according to https://github.com/nickmerwin/node-coveralls#github-actions-ci we are missing a branch env variable for github actions coverage support.
> Fix coverage

- core/include/prometheus/histogram.h
- core/src/histogram.cc
Thanks for the really nice to use library!
Whilst running `heaptrack` against a project that depends on it, I noticed we were allocating/free'ing a lot of memory somewhere. I tracked this down to a loop which was calling `ObserveMultiple`, passing a persistent `std::vector` object each time. I realised that the vector was being copied rather than being passed by reference.
Looking at the implementation of `ObserveMultiple`, it appears that passing by reference was the intention, and it was just a typo to miss the `&`, so this PR adds the missing ref qualifiers.
> Avoid copying the histogram metric buckets.

- core/src/histogram.cc
In a future version of MSVC, \<string> doesn't transitively include\<ostream>.
This port will compile failed with histogram.cc(30): error C2039: 'length_error': is not a member of 'std', so I add include\<ostream> into the source file for fixing this issue.
> Include <ostream> in histogram.cc

- .gitmodules
- cmake/cpp-base64-3rdparty-config.cmake
- pull/CMakeLists.txt
- pull/include/prometheus/exposer.h
- pull/src/basic_auth.cc
- pull/src/basic_auth.h
- pull/src/endpoint.cc
- pull/src/endpoint.h
- pull/src/exposer.cc
- pull/tests/integration/BUILD.bazel
- pull/tests/integration/CMakeLists.txt
- pull/tests/integration/sample_server_auth.cc
Prometheus supports Basic Auth for [scrape targets](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config).
This PR also adds a 3rd party base64 dependency. I've tried to match the existing thirdparty structure when adding it, but happy to change it if it doesn't match the preferred style.
> Add support for HTTP Basic Auth

- .github/workflows/coverage.yml
Understandably, pull requests originating in forks won't get access to secrets in github (in order to prevent them being extracted). This change makes coverage upload only run from PRs or pushes originating in this repo, getting rid of failures for external contributors.
> Fix coverage from forks

- CMakeLists.txt
- cmake/CheckAtomic.cmake
- core/CMakeLists.txt
- pull/include/prometheus/exposer.h
@stackjohn On my Raspberry Pi OS I see the following which triggers the automatic linking of libatomic:
```
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Failed
-- Looking for __atomic_load_8 in atomic
-- Looking for __atomic_load_8 in atomic - found
-- Performing Test HAVE_CXX_ATOMICS_WITH_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITH_LIB - Success
```
Closes: #394
> core: Explicitly link against libatomic when needed

- push/include/prometheus/gateway.h
- push/src/gateway.cc
This PR changes how the push gateway performs http operations by reusing `CURL` handle throughout the lifetime of the gateway object, preserving the underlying tcp connection.
Previously, each collectable iteration would re-create the handle, unnecessarily re-establishing the tcp connection many times during a single run.
> More efficient use of curl by reusing handle across requests

- pull/src/endpoint.cc
- pull/src/endpoint.h
- pull/src/handler.cc
- pull/src/handler.h
A thread registering a `Collectable` with the `Exposer` may end up
invalidating iterators to the `collectables_` vector inside `Endpoint`
while a `CivetServer` handler thread is iterating the vector.
Move the `collectables_` vector to `MetricsHandler` where all accesses
can be guarded by a mutex.
> Avoid race when registering a collectable

- CMakeLists.txt
to select the static runtime use at least CMake 3.15
and pass `-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>`
to CMake when configuring.
Fixes: #410
> feat: allow selection of MSVC runtime library

- core/src/text_serializer.cc
- core/tests/text_serializer_test.cc
This change fixes #407 by increasing precision for rendered floating point numbers
output in the text serializer.
> Fix insufficiently precise value rendering

- core/src/histogram.cc
Without it, the project doesn't compile with `libstdc++-11` (works fine on `libstdc++-10` though).
> Added missing include

- core/src/text_serializer.cc
- core/tests/serializer_test.cc
- core/tests/text_serializer_test.cc
This will result in floating point numbers redered with the
necessary precision and avoids trailing zeroes.
Issue: #441
> fix: use printf %g or std::to_chars to serialize doubles

- .github/workflows/release.yml
This has been tested here: https://github.com/gjasny/prometheus-cpp/releases/tag/v0.0.7
Closes: #388
> ci: Add workflow to create tarball including submodules

- README.md
Hello,
I have recently added prometheus-cpp to conan center reposity.
So I suggest adding reference to it to README.md
Closes: https://github.com/jupp0r/prometheus-cpp/issues/271
> Add conan reference to readme

- core/src/check_names.cc
- core/tests/check_names_test.cc
The std::regex has the problem that it is not available everywhere
and also it's 75 times slower than the naive validity check.
```
BM_Label_Check_Regex          550 ns          550 ns      1270601
BM_Label_Check_NoRegex       7.50 ns         7.50 ns     92802503
```
Issue: #459
> core: Replace name check regex

- core/include/prometheus/family.h
- core/src/family.cc
- core/tests/family_test.cc
If metrics are dynamically added and removed to and from a family (i.e. in a RAII way), there must only be only owner of the reference returned by the `family.Add()` method. To allow this we need to know if a metric with specific labels already exist within the family or likely end up with dangling references.
This relates to #178
> add method to query family if metric already exists

- CMakeLists.txt
For cmake versions older than 3.14, the cpack generation fails at the
top level directory with the following:
CMake Error: The source directory "" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Using cmake 3.14 or newer fixes this.
> CMakeLists: Change cmake min version to 3.14

- cmake/googletest.imp
- core/include/prometheus/detail/ckms_quantiles.h
- core/tests/summary_test.cc
This change removes an unnecessary API constraint that makes it
harder to dynamically construct quantile configurations for summaries.
Fixes #425
> Make summary quantiles non-const

- push/include/prometheus/gateway.h
- push/src/gateway.cc
Pass `std::string` by reference instead of copy (is there a reason why we copy strings here that I missed?).
Explicitly delete special members of `Gateway` class to respect rule of five
> Rule of Five applied on Gateway, avoid unnecessary copies of std::string

- core/include/prometheus/detail/utils.h
- core/include/prometheus/family.h
- core/src/detail/utils.cc
- core/src/family.cc
- core/tests/utils_test.cc
```
before:
BM_Registry_CreateFamily             49.2 ns         49.0 ns     11087352
BM_Registry_CreateCounter/0           165 ns          165 ns      4170191
BM_Registry_CreateCounter/1          1967 ns         1958 ns       556346
BM_Registry_CreateCounter/8          4280 ns         4269 ns       176711
BM_Registry_CreateCounter/64        27091 ns        27009 ns        25755
BM_Registry_CreateCounter/512      224201 ns       223581 ns         3023
BM_Registry_CreateCounter/4096    2056280 ns      2049876 ns          330
after:
BM_Registry_CreateFamily             47.8 ns         47.8 ns     15131733
BM_Registry_CreateCounter/0           158 ns          158 ns      4295006
BM_Registry_CreateCounter/1          1009 ns         1009 ns      1169219
BM_Registry_CreateCounter/8 …
```
> fix(core): gracefully handle label hash collisions

- core/src/detail/utils.cc
- pull/tests/integration/integration_test.cc
Noticed two files where `size_t` was used without the `std::` namespace.
> Add missing std:: on size_t

- core/include/prometheus/histogram.h
- core/include/prometheus/summary.h
- core/src/histogram.cc
- core/src/summary.cc
- Set default values to object fields in header file to limit code duplication as well.
- Mark constructors taking only one parameter as explicit
> Add new constructor for Histogram and Summary taking rvalue ref of parameters

- bazel/repositories.bzl
The second mirror is not working anymore. At the moment, `mirror.bazel.build`'s SSL certificate is expired. This adds another mirror to make zlib available again.
cc @gjasny @jupp0r
> Add third mirror for zlib

- core/tests/summary_test.cc
The Debian Sparc64 builds fail because the expected values
were not within their range:
```
[ RUN      ] SummaryTest.quantile_values
/home/gjasny/prometheus-cpp/core/tests/summary_test.cc:68: Failure
The difference between s.quantile.at(0).value and 0.5 * SAMPLES is 317823, which exceeds 0.05 * SAMPLES, where
s.quantile.at(0).value evaluates to 817823,
0.5 * SAMPLES evaluates to 500000, and
0.05 * SAMPLES evaluates to 50000.
/home/gjasny/prometheus-cpp/core/tests/summary_test.cc:69: Failure
The difference between s.quantile.at(1).value and 0.9 * SAMPLES is 63818, which exceeds 0.01 * SAMPLES, where
s.quantile.at(1).value evaluates to 963818,
0.9 * SAMPLES evaluates to 900000, and
0.01 * SAMPLES evaluates to 10000.
/home/gjasny/prometheus-cpp/core/tests/summary_test.cc:70: Failure
The …
```
> test(core): prevent rotation on slow CPUs

- core/CMakeLists.txt
- core/benchmarks/CMakeLists.txt
- core/benchmarks/info_bench.cc
- core/include/prometheus/client_metric.h
- core/include/prometheus/family.h
- core/include/prometheus/info.h
- core/include/prometheus/metric_type.h
- core/include/prometheus/registry.h
- core/src/detail/builder.cc
- core/src/family.cc
- core/src/info.cc
- core/src/registry.cc
- core/src/text_serializer.cc
- core/tests/builder_test.cc
- core/tests/check_label_name_test.cc
- core/tests/registry_test.cc
- core/tests/text_serializer_test.cc
- pull/tests/integration/sample_server.cc
Hi,
Info is a metric type defined in the [OpenMetrics format](https://github.com/OpenObservability/OpenMetrics/blob/98ae26c87b1c3bcf937909a880b32c8be643cc9b/specification/OpenMetrics.md#info).
It allows to use labels for static information that will not change during the lifetime (for example, versions of the executable/librairies, compilation date...).
In prometheus, it is emulated using a [Gauge with a value 1](https://github.com/prometheus/prometheus/blob/2ce94ac19673a3f7faf164e9e078a79d4d52b767/cmd/promtool/testdata/metrics-test.prom#L33-L35).
After checking, it is not implemented in all the clients, but I've found it in the [Java](https://github.com/prometheus/client_java/blob/2b60c479f57a2f1e20a5bab4dc7131df42327da7/simpleclient/src/main/java/io/prometheus/client/Info.java), …
> feat(core): Add Info metric

- bazel/repositories.bzl
1.2.13 contains a fix for critical CVE https://nvd.nist.gov/vuln/detail/CVE-2022-37434
> chore(push): use zlib 1.2.13

- bazel/civetweb.BUILD
- bazel/curl.BUILD
Bazel 6 flipped the incompatible_use_platforms_repo_for_constraints flag
which causes `@bazel_tools//platforms:*` constraints to fail. The fix is to
use the constraints from `@platforms//*`.
See https://github.com/bazelbuild/bazel/issues/8622 for more details.
Signed-off-by: Vihang Mehta <vihang@pixielabs.ai>
> Update platform constraints to be compatible with bazel 6

- core/include/prometheus/counter.h
- core/include/prometheus/histogram.h
- core/src/counter.cc
- core/src/histogram.cc
- core/tests/counter_test.cc
- core/tests/histogram_test.cc
These reset apis are specifically useful when histograms are collected from different way and then convert them to prometheus metric.
> Add Reset APIs to histogram and counters

- .github/workflows/bazel-ci.yml
Bazel seems to ingest some OpenSSL headers from
/usr/local/include that collide with boringssl.
> ci: disable Bazel on macOS for SSL build

- push/include/prometheus/gateway.h
- push/src/detail/curl_wrapper.cc
- push/src/detail/curl_wrapper.h
- push/src/gateway.cc
Allows specification of a timeout for HTTP requests which is passed to curl. This allows the operation to eventually fail if the remote endpoint does not respond.
Default value for the added parameter maintains existing behaviour.
> feat(push): allow timeout for HTTP requests

- MODULE.bazel
Curl has been publish as a bzlmod.
This use it as a bazel_dep instead of bazel extension
I also used buildifier to format MODULE.bazel and placed dev_dependencies after build dependencies
> Use curl as bazel_dep

- .bazelrc
- pull/BUILD.bazel
- pull/tests/unit/BUILD.bazel
- push/tests/internal/BUILD.bazel
- util/BUILD.bazel
- util/tests/unit/BUILD.bazel
This flag helps find accidental misconfigurations with invalid globs earlier. It's expected to become the default in the next major version of bazel. The BUILD file changes here allow downstream consumers to enable it now.
> build(bazel): Add support for --incompatible_disallow_empty_glob

- CMakeLists.txt
- cmake/project-import-cmake/CMakeLists.txt
Added CMake config to automatically generate version information file. This makes it possible to check if the correct version of the package is installed when the package is consumed.
I'm not sure if the COMPATIBILITY parameter is the one that fits this library best. 
If you like this change and want to merge it just change it to the value you want.
> Add config for basic package version file

- cmake/prometheus-cpp-push.pc.in
- push/CMakeLists.txt
- push/include/prometheus/gateway.h
- push/src/detail/curl_wrapper.cc
- push/src/detail/curl_wrapper.h
- push/src/gateway.cc
I use self-signed certificate, so I need possibility to add extra options for curl.
For example, for disabling check ssl certificate I do:
```	
const prometheus::Labels Labels = prometheus::Gateway::GetInstanceLabel("https://pushgateway.prometheus.localhost");
prometheus::Gateway Gateway{
"https://pushgateway.prometheus.localhost", "", "sample_client", Labels, {}, {}, {},
[&](CURL* curl)
{
curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0);
}
};
```
> Add presetupCurl callback to Gateway.

- .github/workflows/bazel-ci.yml
- .github/workflows/cmake-ci.yml
- .github/workflows/coverage.yml
- .github/workflows/linting.yml
- core/CMakeLists.txt
- pull/CMakeLists.txt
- push/CMakeLists.txt
> build(cmake): fix generator expression
